# Generated by Django 5.2.7 on 2025-10-16 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('imo_number', models.CharField(max_length=10, unique=True)),
                ('type', models.CharField(choices=[('container', 'حاوية'), ('tanker', 'ناقلة'), ('cargo', 'بضائع عامة'), ('passenger', 'ركاب'), ('fishing', 'صيد'), ('other', 'أخرى')], default='container', max_length=20)),
                ('current_latitude', models.FloatField(blank=True, null=True)),
                ('current_longitude', models.FloatField(blank=True, null=True)),
                ('current_speed', models.FloatField(blank=True, null=True)),
                ('current_heading', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='Underway', max_length=50)),
                ('destination_name', models.CharField(blank=True, max_length=100)),
                ('expected_arrival', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('draft', models.FloatField(blank=True, null=True)),
                ('destination_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_ships', to='ships.port')),
            ],
            options={
                'verbose_name': 'سفينة',
                'verbose_name_plural': 'سفن',
                'ordering': ['-last_updated'],
            },
        ),
    ]
