# Generated by Django 5.2.7 on 2025-10-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_name', models.CharField(max_length=120)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('risk_score', models.FloatField()),
                ('message_hash', models.CharField(db_index=True, max_length=64)),
                ('topic_id', models.CharField(blank=True, default='', max_length=64)),
                ('hcs_status', models.CharField(blank=True, default='', max_length=32)),
                ('hcs_tx_id', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
